language: python
python:
  - "2.7"

# Command to install dependencies
install: "pip install -r Test_files/requirements.txt"

# Command to run tests
script: python vespa.py clean -input=Test_files/Genomes

branches:
  only:
    - master
